---
branches:
  - "main"
plugins:
  - - "@semantic-release/commit-analyzer"
    - releaseRules:
        - type: revert
          release: patch
        - type: perf
          release: patch
        - type: build
          scope: deps
          release: patch
        - type: docs
          scope: README.md
          release: patch
        - scope: no-release
          release: false
  - - "@semantic-release/release-notes-generator"
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
      changelogTitle": "# Changelog\n\nAll notable changes to this project will be documented in this file. See\n[Conventional Commits](https://conventionalcommits.org) for commit guidelines."
  - - "@semantic-release/git"
    - message: "chore: Release ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
      assets:
        - CHANGELOG.md
  - - "@semantic-release/github"
    - assets:
        - CHANGELOG.md
preset: conventionalcommits
presetConfig:
  - types:
      - type: feat
        section": Features
      - type: feature,
        ssection": "Features"
      - type: fix
        section: Bug Fixes
      - type: build
        section": Updates to the Build System
        hidden": false
      - type: perf
        section": "Performance Improvements"
      - type: revert
        section: Reverts
      - type: docs
        section: Documentation
      - type: style
        section: Styles
      - type: chore
        section: Miscellaneous Chores
      - type: refactor
        section: Code Refactoring
      - type: test
        section: Tests
      - type: ci
        section: Continuous Integration

